const imagesPath = {
  backgroundImage: "/assets/svg/ctm.png",
  logoNimbleways: "/assets/svg/logoalwan.png",
  userIcon: "/icons/user-filled.svg",
  signinImage: "/assets/images/signin.jpg",
  ciranImage: "/assets/images/ciran.jpg",
  backIcon: "/icons/arrow-left.svg",
  eyeIcon: "/icons/eye.svg",
  addIcon: "/assets/svg/Add.svg",
  darkAddIcon: "/icons/darkAdd.svg",
  logoWithColor: "/assets/svg/logoalwan.png",
  logoWithoutColor: "/assets/svg/logoalwan.png",
  check: "/icons/check.svg",
  cross: "/icons/cross.svg",
  close: "/icons/close.svg",
  priceIcon: "/icons/banknote.svg",
  info: "/icons/info.svg",
  delete: "/icons/delete.svg",
  full: "/icons/fullscreen.svg",
  download: "/icons/download.svg",
  layoutDarkActive: "/icons/activeLayoutDarkMode.svg",
  layoutDarkInactive: "/icons/inactiveLayoutDarkMode.svg",
  layoutLight: "/icons/layoutLightMode.svg",
  ListDarkActive: "/icons/activeListDarkMode.svg",
  ListDarkInactive: "/icons/inactiveListDarkMode.svg",
  ListLight: "/icons/ListLightMode.svg",
  arrowIcon: "/icons/ArrowIcon.svg",
  greyCheck: "/icons/greyCheck.svg",
};

export default imagesPath;
